services:

  redis:
    image: redis:7-alpine # Dùng image alpine cho nhẹ
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - micro_net

#  ## MySQL Docker Compose Config
#  mysql-order:
#    container_name: mysql-order
#    image: mysql:8
#    environment:
#      MYSQL_ROOT_PASSWORD: truongnguyen
#      MYSQL_DATABASE: order-service
#    ports:
#      - "3307:3306"
#    volumes:
#      - order-data:/var/lib/mysql
#    healthcheck:
#      test: [ "CMD-SHELL", 'mysql -h localhost -u root -p$$MYSQL_ROOT_PASSWORD -e "USE `$$MYSQL_DATABASE`"' ]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#      start_period: 180s
#    networks:
#      - micro_net

#  mysql-product:
#    container_name: mysql-product
#    image: mysql:8
#    environment:
#      MYSQL_ROOT_PASSWORD: truongnguyen
#      MYSQL_DATABASE: product-service
#    ports:
#      - "3308:3306"
#    volumes:
#      - product-data:/var/lib/mysql
#    healthcheck:
#      test: [ "CMD-SHELL", 'mysql -h localhost -u root -p$$MYSQL_ROOT_PASSWORD -e "USE `$$MYSQL_DATABASE`"' ]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#      start_period: 180s
#    networks:
#      - micro_net

#  mysql-inventory:
#    container_name: mysql-inventory
#    image: mysql:8
#    environment:
#      MYSQL_ROOT_PASSWORD: truongnguyen
#      MYSQL_DATABASE: inventory-service
#    ports:
#      - "3309:3306"
#    volumes:
#      - inventory-data:/var/lib/mysql
#    healthcheck:
#      test: [ "CMD-SHELL", 'mysql -h localhost -u root -p$$MYSQL_ROOT_PASSWORD -e "USE `$$MYSQL_DATABASE`"' ]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#      start_period: 180s
#    networks:
#      - micro_net

  ## Keycloak Config with Mysql database
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8
    volumes:
      - keycloak-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -proot" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - micro_net

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:18.0.0
    command: [ "start-dev", "--import-realm" ]
    environment:
      # Biến CSDL (Phải bắt đầu bằng KC_)
      KC_DB: mysql
      KC_DB_URL_HOST: keycloak-mysql
      KC_DB_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      # Biến Admin (Phải bắt đầu bằng KC_)
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # Biến Cổng và Hostname (Phải bắt đầu bằng KC_)

      # Đây là biến ĐÚNG để đổi cổng (thay cho QUARKUS_HTTP_PORT)
      KC_HTTP_PORT: 8085

      KC_HOSTNAME: keycloak
      KC_HOSTNAME_URL: http://keycloak:8085
      KC_HOSTNAME_STRICT: "false"

    ports:
      - "8085:8085"
    volumes:
      - ./keycloak-data:/opt/keycloak/data/import
    depends_on:
      keycloak-mysql:
        condition: service_healthy
    networks:
      - micro_net

#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.0.1
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      KAFKA_HEAP_OPTS: "-Xms1G -Xmx1G"
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    healthcheck:
#      test: ["CMD-SHELL", "echo 'srvr' | nc -w 2 localhost 2181 | grep 'Mode:'"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 20s
#    networks:
#      - micro_net

#  broker:
#    image: confluentinc/cp-kafka:7.0.1
#    container_name: broker
#    ports:
#      - "9092:9092"
#    depends_on:
#      zookeeper:
#        condition: service_healthy
#    environment:
#      KAFKA_HEAP_OPTS: "-Xms1G -Xmx1G"
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
#      # THÊM: Chỉ định listener nào  broker khác giao tiếp
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
#
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_DELETE_TOPIC_ENABLE: "true"
#    healthcheck:
#      # SỬA: Healthcheck nên dùng listener nội bộ
#      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server broker:29092 --list" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 20s
#    networks:
#      - micro_net

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"

      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server kafka:29092 --list || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - micro_net

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.0
    container_name: schema-registry
    ports:
      - "8081:8081"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:29092"
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
    networks:
      - micro_net


  #  ## Eureka Server
#  discovery-server:
#    image: truongnguyen3006/discovery-server:latest
#    container_name: discovery-server
#    ports:
#      - "8761:8761"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - micro_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # Cổng của Prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Mount file config
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - micro_net

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000" # Cổng của Grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - micro_net

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - micro_net

    # Service Nginx
  nginx:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - "8000:80" # Mở cổng 80 ra ngoài
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount file config vào
    extra_hosts:
      - "host.docker.internal:host-gateway" # Bắt buộc cho Linux (Windows Docker Desktop tự có, nhưng thêm vào cho chắc)
    networks:
      - micro_net


#  api-gateway:
#    image: truongnguyen3006/api-gateway:latest
#    container_name: api-gateway
#    ports:
#      - "8181:8080"
#    environment:
#      #cho phép chọn profile cấu hình phù hợp. docker (application-docker.yml hoặc .properties)
#      - SPRING_PROFILES_ACTIVE=docker
#      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
#      - eureka.client.serviceUrl.defaultZone=http://eureka:password@discovery-server:8761/eureka
#      - spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8085/realms/spring-boot-microservices-realm
#    depends_on:
#      - discovery-server
#      - keycloak
#    networks:
#      - micro_net
  ## Product-Service Docker Compose Config
#  product-service:
#    container_name: product-service
#    image: truongnguyen3006/product-service:latest
#    ports:
#      - "8083:8083"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-product:3306/product-service
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: truongnguyen
#      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.MySQL8Dialect # Lưu ý: Thường là spring.jpa.database-platform
#      SPRING_PROFILES_ACTIVE: docker
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:password@discovery-server:8761/eureka
#      SPRING_DATA_REDIS_HOST: redis     # <-- Sửa thụt lề ở đây
#      SPRING_DATA_REDIS_PORT: 6379
#    depends_on:
#      mysql-product:
#        condition: service_healthy
#      discovery-server:
#        condition: service_started
#      api-gateway:
#        condition: service_started
#      redis:
#        condition: service_started
#    networks:
#      - micro_net

#  ## Notification-Service Docker Compose Config
#  notification-service:
#    container_name: notification-service
#    image: truongnguyen3006/notification-service:latest
#    environment:
##      SPRING_PROFILES_ACTIVE: docker
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:password@discovery-server:8761/eureka
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:29092
#    depends_on:
#      - broker
#      - discovery-server
#      - api-gateway
#    networks:
#      - micro_net

#  ## Order-Service Docker Compose Config
#  order-service:
#    container_name: order-service
#    image: truongnguyen3006/order-service:latest
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-order:3306/order-service
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: truongnguyen
#      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.MySQL8Dialect
#      SPRING_PROFILES_ACTIVE: docker
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:password@discovery-server:8761/eureka
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:29092
#    depends_on:
#      mysql-order:
#        condition: service_healthy # <-- Sửa ở đây
#      broker:
#        condition: service_healthy
#      discovery-server:
#        condition: service_started
#      api-gateway:
#        condition: service_started
#    networks:
#      - micro_net
#  ## Inventory-Service Docker Compose Config

#  inventory-service:
#    container_name: inventory-service
#    image: truongnguyen3006/inventory-service:latest
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-inventory:3306/inventory-service
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: truongnguyen
#      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.MySQL8Dialect
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:password@discovery-server:8761/eureka
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:29092
#    depends_on:
#      mysql-inventory:
#        condition: service_healthy
#      discovery-server:
#        condition: service_started
#      api-gateway:
#        condition: service_started
#      broker:
#        condition: service_healthy
#    networks:
#      - micro_net

# --- KHAI BÁO TẤT CẢ CÁC NAMED VOLUMES ---
volumes:
  product-data:
  order-data:
  #  user-data:
  inventory-data:
  keycloak-db-data:
#Định nghĩa network
networks:
  micro_net:
    driver: bridge
