services:
  ## MySQL Docker Compose Config
#  mysql-order:
#    container_name: mysql-order
#    image: mysql:8
#    environment:
#      MYSQL_ROOT_PASSWORD: truongnguyen
#      MYSQL_DATABASE: order-service
#      TZ: Asia/Ho_Chi_Minh
#    ports:
#      - "3307:3306"
#    volumes:
#      - order-data:/var/lib/mysql
##      - ./mysql-init:/docker-entrypoint-initdb.d
#    healthcheck:
#      test: [ "CMD-SHELL", 'mysql -h localhost -u root -p$$MYSQL_ROOT_PASSWORD -e "USE `$$MYSQL_DATABASE`"' ]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#      start_period: 180s
#    networks:
#      - micro_net

  mysql-product:
    container_name: mysql-product
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: truongnguyen
# lệnh cho image mysql tự động tạo một database rỗng
      MYSQL_DATABASE: product-service
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3308:3306"
    volumes:
      - product-data:/var/lib/mysql
#      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", 'mysql -h localhost -u root -p$$MYSQL_ROOT_PASSWORD -e "USE `$$MYSQL_DATABASE`"' ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 180s
    networks:
      - micro_net


#  mysql-inventory:
#    container_name: mysql-inventory
#    image: mysql:8
#    environment:
#      MYSQL_ROOT_PASSWORD: truongnguyen
#      MYSQL_DATABASE: inventory-service
#      TZ: Asia/Ho_Chi_Minh
#    ports:
#      - "3309:3306"
#    volumes:
#      - inventory-data:/var/lib/mysql
##      - ./mysql-init:/docker-entrypoint-initdb.d
#    healthcheck:
#      test: [ "CMD-SHELL", 'mysql -h localhost -u root -p$$MYSQL_ROOT_PASSWORD -e "USE `$$MYSQL_DATABASE`"' ]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#      start_period: 180s
#    networks:
#      - micro_net

  ## Keycloak Config with Mysql database
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8
    volumes:
#      - ./mysql_keycloak_data:/var/lib/mysql
      - keycloak-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    # healthcheck phải ngang hàng với environment
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -proot" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - micro_net

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:18.0.0
    command: [ "start-dev" ]
    environment:
      # Biến CSDL (Phải bắt đầu bằng KC_)
      KC_DB: mysql
      KC_DB_URL_HOST: keycloak-mysql
      KC_DB_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      # Biến Admin (Phải bắt đầu bằng KC_)
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # Biến Cổng và Hostname (Phải bắt đầu bằng KC_)

      # Đây là biến ĐÚNG để đổi cổng (thay cho QUARKUS_HTTP_PORT)
      KC_HTTP_PORT: 8085

      KC_HOSTNAME: keycloak
      KC_HOSTNAME_URL: http://keycloak:8085
      KC_HOSTNAME_STRICT: "false"

    ports:
      - "8085:8085"
    depends_on:
      keycloak-mysql:
        condition: service_healthy
    networks:
      - micro_net


#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.0.1
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    networks:
#      - micro_net
#
#
#  broker:
#    image: confluentinc/cp-kafka:7.0.1
#    container_name: broker
#    ports:
#      - "9092:9092"
#    depends_on:
#      - zookeeper
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#    networks:
#      - micro_net


  # Zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - SERVER_PORT=9411
      - SERVER_ADDRESS=0.0.0.0
    ports:
      - "9411:9411"
    networks:
      - micro_net


  ## Eureka Server
  discovery-server:
    image: truongnguyen3006/discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
    depends_on:
      - zipkin
    networks:
      - micro_net

  api-gateway:
    image: truongnguyen3006/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8181:8080"
    environment:
      #cho phép chọn profile cấu hình phù hợp. docker (application-docker.yml hoặc .properties)
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
      - eureka.client.serviceUrl.defaultZone=http://eureka:password@discovery-server:8761/eureka
      - management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
      - spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8085/realms/spring-boot-microservices-realm
    depends_on:
      - zipkin
      - discovery-server
      - keycloak
    networks:
      - micro_net

  ## Product-Service Docker Compose Config
  product-service:
    container_name: product-service
    image: truongnguyen3006/product-service:latest
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-product:3306/product-service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: truongnguyen
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:password@discovery-server:8761/eureka
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

    depends_on:
      mysql-product:
        condition: service_healthy # <-- Sửa ở đây
      discovery-server:
        condition: service_started
      api-gateway:
        condition: service_started
    networks:
      - micro_net

#  ## Order-Service Docker Compose Config
#  order-service:
#    container_name: order-service
#    image: truongnguyen3006/order-service:latest
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      # Ghi đè trực tiếp URL của database
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-order:3306/order-service
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: truongnguyen
#      # Ghi đè Dialect để sửa lỗi "Unable to determine Dialect"
#      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.MySQL8Dialect
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:password@discovery-server:8761/eureka
#    depends_on:
#      mysql-order:
#        condition: service_healthy # <-- Sửa ở đây
#      broker:
#        condition: service_started
#      zipkin:
#        condition: service_started
#      discovery-server:
#        condition: service_started
#      api-gateway:
#        condition: service_started
#    networks:
#      - micro_net
#
#  ## Inventory-Service Docker Compose Config
#  inventory-service:
#    container_name: inventory-service
#    image: truongnguyen3006/inventory-service:latest
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-inventory:3306/inventory-service
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: truongnguyen
#      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.MySQL8Dialect
#      SPRING_PROFILES_ACTIVE: docker
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:password@discovery-server:8761/eureka
#    depends_on:
#      mysql-inventory:
#        condition: service_healthy # <-- Sửa ở đây
#      discovery-server:
#          condition: service_started
#      api-gateway:
#          condition: service_started
#    networks:
#      - micro_net
#
#  ## Notification-Service Docker Compose Config
#  notification-service:
#    container_name: notification-service
#    image: truongnguyen3006/notification-service:latest
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - eureka.client.serviceUrl.defaultZone=http://eureka:password@discovery-server:8761/eureka
#    depends_on:
#      - zipkin
#      - broker
#      - discovery-server
#      - api-gateway
#    networks:
#      - micro_net
#
#  ## Prometheus
#  prometheus:
#    image: prom/prometheus:v2.37.1
#    container_name: prometheus
#    restart: always
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#    networks:
#      - micro_net
#
#  grafana:
#    image: grafana/grafana-oss:8.5.2
#    container_name: grafana
#    restart: always
#    ports:
#      - "3000:3000"
#    links:
#      - prometheus:prometheus
#    volumes:
#      - ./grafana:/var/lib/grafana
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=password
#    networks:
#      - micro_net
# --- KHAI BÁO TẤT CẢ CÁC NAMED VOLUMES ---
volumes:
  product-data:
  order-data:
#  user-data:
  inventory-data:
  keycloak-db-data:
#Định nghĩa network
networks:
  micro_net:
    driver: bridge
